### ISSUE TITLE
A macro is not being generated properly

### ISSUE THREAD

**Issue by thelinuxlich** [itsMapleLeaf/vite-plugin-babel-macros#3]
I have a project using vite-plugin-babel-macros and a macro within valtio: https://github.com/thelinuxlich/react-modern-starter

When I run `yarn dev` Vite will try to use the plugin for the Nav.jsx file and throw this error:

`[vite] Internal server error: /home/thelinuxlich/frontend-starter/src/components/Nav.jsx: valtio/macro: Cannot read property '0' of undefined `

**Comment by itsMapleLeaf** [comment]
Hm, at a glance, the error seems to get raised by this line: https://github.com/pmndrs/valtio/blob/master/src/macro.ts#L10

Can you try this in another macro setup (e.g., create-react-app) and see if it works there?

**Comment by itsMapleLeaf** [comment]
In general, try to narrow this down a bit to see what causes the error to pop up. I added a few more tests, and it still doesn't _seem_ like it's an issue specifically with this plugin. It could be the macro itself, in combination with something else, etc.
