### ISSUE TITLE
Allow to change babelrc value from outside the plugin

### ISSUE THREAD

**Issue by MathieuMathurin** [itsMapleLeaf/vite-plugin-babel-macros#5]
We are using Lingui Trans component and one of our id has an UTF-8 character. 

Before switching to Vite and your plugin, we had this build output

```
j.a.createElement(O.Trans, {
    id: "C’est un example.",
})
```

But now we get this output where the unicode text gets escaped.

```
j.a.createElement(O.Trans, {
    id: "C\\u2019est un example.",
})
```

To solve this issue, we need this babel config
```
{
  "generatorOpts": {
    "jsescOption": {
      "minimal": true
    }
  }
}
```

But we currently can't tell the macrosPlugin to use a .babelrc file.

PS: I made the changes locally and have a PR ready but I'm not allowed to push a new branc.

**Comment by MathieuMathurin** [comment]
I don't want the ability to do custom babel configs, I want to the possibility to tell babel to use custom configs. Something like this

```
import * as babel from "@babel/core"
import type { TransformResult } from "vite"

const sourceRegex = /\.(j|t)sx?$/
const tsxRegex = /\.(j|t)sx$/ // all files are being interpreted as TS, so we'll treat JSX as TSX

export default function macrosPlugin({ babelrc = false } : { babelrc?: boolean }) {
	return {
		name: "babel-macros",
		enforce: "pre",
		async transform(source: string, filename: string) {
			if (filename.includes("node_modules")) {
				return undefined
			}

			if (!sourceRegex.test(filename)) {
				return undefined
			}

			const result = await babel.transformAsync(source, {
				filename,
				plugins: [
					require.resolve("@babel/plugin-syntax-jsx"),
					[
						require.resolve("@babel/plugin-syntax-typescript"),
						{ isTSX: tsxRegex.test(filename) },
					],
					require.resolve("babel-plugin-macros"),
				],
				babelrc,
				configFile: false,
				sourceMaps: true,
			})
			return result as TransformResult | null
		},
	} as const
}

```

**Comment by itsMapleLeaf** [comment]
I don't see how that's different from the PR 😅 If you need tighter babel configuration, you should use the babel rollup plugin

**Comment by MathieuMathurin** [comment]
generatorOpts config have an impact on the code generated by babel-plugin-macros. Which I think is directly related with the purpose on this vite plugin.

Thank you for your suggested alternative 👍
