### ISSUE TITLE
can't use with `@vitejs/plugin-react`

### ISSUE THREAD

**Issue by shlroland** [itsMapleLeaf/vite-plugin-babel-macros#7]
#6 same issue

**Comment by itsMapleLeaf** [comment]
Can you share the error messages you're getting, if any?

**Comment by quolpr** [comment]
You can enable babel macros for react with this code:

```
    react({
      fastRefresh: false,
      babel: {
        plugins: ['babel-plugin-macros'],
        parserOpts: {
          plugins: ['decorators-legacy'],
        },
      },
    }),

```

**Comment by pedrosimao** [comment]
> You can enable babel macros for react with this code:
> 
> ```
>     react({
>       babel: {
>         plugins: ['babel-plugin-macros']
>       },
>     }),
> ```

This works for me, but Jest tests will fail while using emotion styled function for example:

```
TypeError: (0 , macro_1.default) is not a function
```

Any ideas on how to fix this?

**Comment by itsMapleLeaf** [comment]
> > You can enable babel macros for react with this code:
> > ```
> >     react({
> >       babel: {
> >         plugins: ['babel-plugin-macros']
> >       },
> >     }),
> > ```
> 
> This works for me, but Jest tests will fail while using emotion styled function for example:
> 
> ```
> TypeError: (0 , macro_1.default) is not a function
> ```
> 
> Any ideas on how to fix this?

I would recommend switching to Vitest https://vitest.dev/

**Comment by fpigeonjr** [comment]
> You can enable babel macros for react with this code:
> 
> ```
>     react({
>       babel: {
>         plugins: ['babel-plugin-macros']
>       },
>     }),
> ```

Confirmed, this worked for me as well. 
Wonder why this isn't documented in the `README`?

**Comment by itsMapleLeaf** [comment]
> > You can enable babel macros for react with this code:
> > ```
> >     react({
> >       babel: {
> >         plugins: ['babel-plugin-macros']
> >       },
> >     }),
> > ```
> 
> Confirmed, this worked for me as well. Wonder why this isn't documented in the `README`?

Because no one suggested to do so! 😅 I'll go ahead and take care of that

**Comment by fpigeonjr** [comment]
🥇thanks @itsMapleLeaf that would be helpful as it took me awhile to find this. It would be nice to have an example of how to setup for React based projects.
