### ISSUE TITLE
Version 1.0.6 break changes

### ISSUE THREAD

**Issue by kamikazebr** [itsMapleLeaf/vite-plugin-babel-macros#9]
With the enforce node version higher than 16, it breaks when using node 14.

Maybe it should be semver major? or even minor with releases notes?

https://github.com/itsMapleLeaf/vite-plugin-babel-macros/blob/main/package.json#L46

**Comment by itsMapleLeaf** [comment]
Ah, you're right, this definitely should have been a major. I don't think it's worth making a new release, but I'll update the releases.
